"use client";
import { useRef, useState } from "react";
import { Bold, ImageUp, Italic, Link as LinkIcon, List, Save, Send, Underline } from "lucide-react";
import { useRouter } from "next/navigation";

export function AnnouncementForm() {
  const router=useRouter(); const editor=useRef<HTMLTextAreaElement>(null); const[body,setBody]=useState(""); const[status,setStatus]=useState<"DRAFT"|"PUBLISHED">("DRAFT"); const[image,setImage]=useState<string|null>(null); const[imageName,setImageName]=useState(""); const[error,setError]=useState(""); const[busy,setBusy]=useState(false);
  function format(before:string,after=before){const el=editor.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;setBody(body.slice(0,start)+before+body.slice(start,end)+after+body.slice(end));requestAnimationFrame(()=>{el.focus();el.setSelectionRange(start+before.length,end+before.length)})}
  function readImage(file?:File){if(!file)return;if(file.size>5_000_000){setError("Featured image must be 5MB or smaller.");return}const reader=new FileReader();reader.onload=()=>{setImage(String(reader.result));setImageName(file.name)};reader.readAsDataURL(file)}
  async function save(form:HTMLFormElement,status:"DRAFT"|"PUBLISHED"){setBusy(true);setError("");const data=Object.fromEntries(new FormData(form));const response=await fetch("/api/admin/announcements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...data,body,status,featuredImage:image})});const result=await response.json();if(response.ok){form.reset();setBody("");setImage(null);setImageName("");router.refresh()}else setError(result.message);setBusy(false)}
  return <form className="admin-card admin-form post-editor-card" onSubmit={e=>{e.preventDefault();save(e.currentTarget,status)}}><h2>Post Details</h2><p>Compose and publish a message for voters and candidates.</p><label>Post Title<input name="title" placeholder="Enter post title..." required/></label><div className="post-meta"><label>Category<select name="category"><option>Announcement</option><option>Election Update</option><option>Candidate News</option></select></label><fieldset><legend>Status</legend><label><input type="radio"name="publicationStatus"checked={status==="DRAFT"}onChange={()=>setStatus("DRAFT")}/>Draft</label><label><input type="radio"name="publicationStatus"checked={status==="PUBLISHED"}onChange={()=>setStatus("PUBLISHED")}/>Published</label></fieldset></div><label>Content<div className="editor-shell"><div className="editor-toolbar"><button type="button"onClick={()=>format("**")}aria-label="Bold"><Bold/></button><button type="button"onClick={()=>format("_")}aria-label="Italic"><Italic/></button><button type="button"onClick={()=>format("__")}aria-label="Underline"><Underline/></button><i/><button type="button"onClick={()=>format("[","](https://)")}aria-label="Add link"><LinkIcon/></button><button type="button"onClick={()=>format("- ","")}aria-label="List"><List/></button></div><textarea ref={editor}value={body}onChange={e=>setBody(e.target.value)}name="body"placeholder="Write your announcement or blog post content here..."required/></div></label><label>Featured Image<span className="post-image-upload"><ImageUp/><strong>{imageName||"Click to upload a featured image"}</strong><small>PNG, JPG or WEBP · Max 5MB</small><input type="file"accept="image/png,image/jpeg,image/webp"onChange={e=>readImage(e.target.files?.[0])}/></span></label>{error&&<p className="error">{error}</p>}<div className="form-actions"><button type="button"disabled={busy}onClick={e=>save(e.currentTarget.form!,"DRAFT")}><Save/> Save as Draft</button><button type="button"className="button"disabled={busy}onClick={e=>save(e.currentTarget.form!,"PUBLISHED")}><Send/> Publish Post</button></div></form>
}
